spring:
  flyway:
    locations: classpath:/db/migration
    baseline-version: 0
    placeholders:
      email-suffix: .vn
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: 12345678
  mail:
    host: smtp.gmail.com
    port: 587
    username: lenguyencm97@gmail.com
    password: elnn eihl ztjh mnju
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  jpa:
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9292
import:
  directory: relative/com/restapi/excel/importfiles


