CREATE TABLE IF NOT EXISTS "users_tbl" (
  "id" SERIAL PRIMARY KEY,
  "username" VARCHAR(255) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "first_name" VARCHAR(255) NULL,
  "last_name" VARCHAR(255) NULL,
  "address" VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS "roles_tbl" (
    "id" SERIAL PRIMARY KEY,
    "name" VARCHAR(255) UNIQUE NOT NULL
);
